# -*- coding: utf-8 -*-
"""2 mark assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNK_PMRmh9Tqtd6hKraMoUDLXnHU-oxq
"""

def sum_up(num1,num2,num3):
  return num1+num2+num3
def make_cube(num):
  return num**3
def make_power(num,power):
  return num**power
num1=int(input("num1:"))
num2=int(input("num2:"))
num3=int(input("num3:"))
power=int(input("power:"))
num4=int(sum_up(num1,num2,num3))
num5=int(make_cube(num4))
num6=int(make_power(num4,power))
print("sum:",num4)
print("cube:",num5)
print("power:", num6)